### ISSUE TITLE
cant uninstall the game after use for the latest update

### ISSUE THREAD

**Issue by MacOzone** [kinsi55/BeatSaber_UpdateSkipper#13]
I used it for the latest update. Steam shown it needed to download files but it wont start. Then I tried to verify the game and tried to uninstall it. Both of them wont work and steam just keep loading. I also tried delet the game folder and it wont help.

**Comment by kinsi55** [comment]
I just tried it myself for the latest update and it works with no issues - I couldnt tell you what could have gone wrong for you.

One thing you can try is to delete the `appmanifest_620980.acf` file in your steamapps folder (two folders up from the beatsaber one) and see if that helps.

**Comment by MacOzone** [comment]
It works, thx
