### ISSUE TITLE
Manifest ID not working.

### ISSUE THREAD

**Issue by longwolfdude** [kinsi55/BeatSaber_UpdateSkipper#15]
As of writing, there was a new beat saber update 5 hours ago with a Manifest ID that is 18 digits instead of 19 so I get an error on the update skipper.
![Screenshot 2023-04-04 162202](https://user-images.githubusercontent.com/74474209/229911511-710e4a9c-8675-421a-b349-eb75db046856.png)

**Comment by kinsi55** [comment]
Your Version of the Update Skipper is oudated, grab the latest one ;)
