### ISSUE TITLE
doesnt work on 1.17.1 update :(

### ISSUE THREAD

**Issue by putnamto** [kinsi55/BeatSaber_UpdateSkipper#4]
yeah, like the title says, it worked on the update before....i think... the one before skrillex, but it doesnt work on this recent update.

**Comment by kinsi55** [comment]
How does it not work? There havent been any changes to Steam which would cause that

**Comment by putnamto** [comment]
i honestly dont know, i ran the update blocker, it told me to close steam,
i closed steam, ran it again, it said it was ok, opened steam back up and
it still said update required for the game.

i ended up updating because the mods from 1.17.0 still work on 1.17.1

**Comment by kinsi55** [comment]
In some cases its normal for Steam to still say update required - Clicking the Update button will then however do nothing. I guess that is what happened in your case and had somebody else curious about this and message me, and that is what happened to him, so I'll close this here.
