### ISSUE TITLE
Fails with 18 digit ManifestID from today's update.

### ISSUE THREAD

**Issue by NjnaGrimsdottir** [kinsi55/BeatSaber_UpdateSkipper#9]
![image](https://user-images.githubusercontent.com/841771/179022569-bc34f16b-6038-4f39-8635-d4c58b853d9e.png)

![image](https://user-images.githubusercontent.com/841771/179022611-59cca517-c112-4ee8-9843-20e15d4ad89a.png)

Failure due to structural change in ManifestID.. 18 vs.. 19 digit length.

**Comment by NjnaGrimsdottir** [comment]
Even adding a 0 in front of the number does not solve the issue.  Still detects an update available.

**Comment by kinsi55** [comment]
Releasing update in a minute
